name: prune
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pip:
      - accelerate>=1.12.0
      - matplotlib>=3.10.8
      - mslk>=0.0.0
      - numpy>=2.2.6
      - opencv-python>=4.13.0.92
      - pandas>=2.3.3
      - pyyaml>=6.0.3
      - scikit-image>=0.25.2
      - tensorboard>=2.20.0
      - torchao>=0.16.0
      - tqdm>=4.67.3
      - transformers>=5.2.0
      - wandb>=0.25.0
      - -e .
