# setting.yaml
# basic settings file for the project

# Required
#image_root: "/media/jim/Ironwolf/datasets/scand_data/images"
image_root: "/fs/gamma-datasets/SCAND/images"
#preference_root: "/media/jim/Ironwolf/datasets/scand_data/chop_annotations"
preference_root: "/fs/nexus-scratch/jianyu34/Downloads/chop_annotations"
calibration_file : "../config/tf.json"
image_ext: "png"
verbose: false
plot_imgs: false
device: "cuda"
project_name : "Prune"
entity : "jianyu34-university-of-maryland"
learning_rate: 2.5e-3
batch_size: 512   # 512 = 14GB VRAM, 50GB RAM
epochs: 200
num_queries: 1
hidden_dim: 1024
num_workers: 4  # if local, recommend no more than 3 @ batch_size 512
num_heads: 4
save_mode": false
batch_print_freq: 5
checkpoint_freq: 5
dropout: 0.1
sweep: false
use_cls: false
use_wandb: true
warmup_epochs: 3
cosine_LR_T: 10
cosine_LR_mult: 2
gradient_log_freq : 50
checkpoint_dir : "../models/checkpoints/"
load_checkpoint_path : ""

